Algoritmo "Exercicio07_Dobro_Terca"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Lê um número real e exibe o seu dobro e a sua terça parte
// Autor(a)    : Luiz Henrique Santos Aragao
// Data atual  : 22/03/2026
Var
n, d, t: real

Inicio

// Entrada de Dados
escreva("Digite um numero: ")
leia(n)

//Processamento
d <- n * 2
t <- n / 3

//Saida de Dados
escrevaL("O dobro de ", n, " é ", d)
escrevaL("A terça parte de ", n, " é ", t)

Fimalgoritmo